# SQLite version 3.x
#   gem install sqlite3
development:
  adapter: mysql2
  database: xyz_development
  pool: 50
  encoding: utf8
  username: 
  password: 
  host: localhost

production:
  adapter: mysql2
  database: xyz_production
  pool: 5
  encoding: utf8
  username: 
  password: 
